config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: :homes_about

  get '/search' => 'searches#search'

  resources :books, except: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :chats, only: [:show, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  is_impressionable counter_cache: true

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :follower, source: :followed
  has_many :followers, through: :followed, source: :follower
  
  has_many :group_users
  has_many :groups, through: :group_users
  
  has_many :user_rooms
  has_many :chats
  
  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  impressionist :actions => [:show]

  def index
    @book = Book.new
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorites).sort {|a,b|
      b.favorites.where(created_at: from...to).size <=>
      a.favorites.where(created_at: from...to).size
    }
    if params[:sort].present?
      case params[:sort]
      when 'new'
        @books = Book.all.order(created_at: 'DESC')
      when 'old'
        @books = Book.all.order(created_at: 'ASC')
      when 'high'
        @books = Book.all.order(rate: 'DESC')
      end
    end
  end

  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(book)
    else
      @book = book
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    impressionist(@book, nil, unique: [:session_hash.to_s])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(book)
    else
      @book = book
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end
  
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private
  
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render 'new'
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to  groups_path
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end

  def new_mail
    @group = Group.find(params[:group_id])
  end

  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @title = params[:title]
    @content = params[:content]
    EventMailer.send_mail(group_users, @title, @content).deliver
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Editing Group</h3>
      <%= form_with model: @group, local: true do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.attachment_field :image %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Group", class: 'btn btn-info' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0 py-3">
  <div class="row">
    <%= render 'books/list', book: @book, user: current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <table class="table">
        <tr>
          <th></th>
          <th>グループ名</th>
          <th>紹介文</th>
          <th></th>
        </tr>
        <% @groups.each do |group| %>
        <tr>
          <td><%= attachment_image_tag(group, :image, size: "50x50", fallback: "no_image.jpg") %></td>
          <td><%= link_to group.name, group_path(group) %></td>
          <td><%= group.introduction %></td>
          <td>
            <% if group.owner_id == current_user.id %>
              <%= link_to 'Edit', edit_group_path(group), class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
      <%= form_with model: @group, local: true do |f| %>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.attachment_field :image %>
        </div>
        <div class="form-group">
          <%= f.submit "Create Group", class: 'btn btn-info' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Event Mail</h3>
        <%= form_with url: group_send_mail_path(@group), method: :get, local:true do |f| %>
          <div class="form-group">
            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control book_title' %>
          </div>
          <div class="form-group">
            <%= f.label :content %>
            <%= f.text_area :content, class: 'form-control book_body' %>
          </div>
          <div class="form-group text-right">
            <%= f.submit "送信", class: 'btn btn-success' %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto my-3">
      <h3 class="margin_top text-center">送信が完了しました</h3>
      <div class="margin_top">内容は以下の通りです。</div>
      <div class="small_margin_top">
        [タイトル]<p class="font-weight-bold"> <%= @title %></p>
      </div>
      <div>
        [本文]<p class="font-weight-bold"> <%= safe_join(@content.split("\n"),tag(:br)) %></p>
      </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <%= render 'books/list', book: @book, user: current_user %>
    <div class='col-md-8 offset-md-1'>
      <h2>Group Detail</h2>
      <table class='table'>
        <tr>
          <td><%= attachment_image_tag(@group, :image, size: "50x50", fallback: "no_image.jpg") %></td>
          <td>
            <% @group.users.each do |member| %>
              <%= member.name %><br>
            <% end %>
          </td>
          <td><%= @group.introduction %></td>
          <td>
            <% if @group.users.include?(current_user) %>
              <%= link_to 'Leave this group', group_path(@group), method: :delete, class: "btn btn-sm btn-danger" %>
            <% else %>
              <%= link_to 'Join this group', group_join_path(@group), class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
          <% if @group.owner_id == current_user.id %>
            <td><%= link_to 'Notice an Event', group_new_mail_path(@group),class: "btn btn-sm btn-info" %></td>
            <td><%= link_to 'Edit', edit_group_path(@group), class: "btn btn-sm btn-success" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>