config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'homes#top'
  get 'home/about' => 'homes#about', as: :homes_about

  get '/search' => 'searches#search'

  resources :books, except: [:new] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "search", to: "users#search"
  end

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  resources :chats, only: [:show, :create]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  is_impressionable counter_cache: true

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users

  validates :name, presence: true
  validates :introduction, presence: true
  attachment :image, destroy: false
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :follower, source: :followed
  has_many :followers, through: :followed, source: :follower
  
  has_many :group_users
  has_many :groups, through: :group_users
  
  has_many :user_rooms
  has_many :chats
  
  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  impressionist :actions => [:show]

  def index
    @book = Book.new
    to = Time.current.at_end_of_day
    from = (to - 6.day).at_beginning_of_day
    @books = Book.includes(:favorites).sort {|a,b|
      b.favorites.where(created_at: from...to).size <=>
      a.favorites.where(created_at: from...to).size
    }
    if params[:sort].present?
      case params[:sort]
      when 'new'
        @books = Book.all.order(created_at: 'DESC')
      when 'old'
        @books = Book.all.order(created_at: 'ASC')
      when 'high'
        @books = Book.all.order(rate: 'DESC')
      end
    end
  end

  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(book)
    else
      @book = book
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    impressionist(@book, nil, unique: [:session_hash.to_s])
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    book = Book.find(params[:id])
    if book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(book)
    else
      @book = book
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate)
  end
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
  end
  
  def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
    redirect_to request.referer
  end

  private
  
  def chat_params
    params.require(:chat).permit(:message, :room_id)
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page])
    @today_books = @books.where(created_at: Time.current.all_day)
    @yesterday_books = @books.where(created_at: 1.day.ago.all_day)
    @this_week_books = @books.where(created_at: 6.day.ago.at_beginning_of_day...Time.current.at_end_of_day)
    @last_week_books = @books.where(created_at: 13.day.ago.at_beginning_of_day...1.week.ago.at_end_of_day)
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(user)
    else
      @user = user
      render :edit
    end
  end
  
  def search
    @user = User.find(params[:user_id])
    @books = @user.books
    @book = Book.new
    if params[:created_at] == ""
      @search_book = "日付を選択してください"
    else
      create_at = params[:created_at]
      @search_book = @books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<div class="col-md-3">
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg", class: "my-3" %>
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
        <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <th>
          <%= link_to user_followings_path(user) do %>
            <%= user.followings.count %>
          <% end %>
          </th>
      </tr>
      <tr>
        <th>followers</th>
        <th>
          <%= link_to user_followers_path(user) do %>
            <%= user.followers.count %>
          <% end %>
        </th>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <% if current_user == user %>
      <%= link_to "", edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
    <% else %>
      <% if current_user.following?(user) %>
        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-sm btn-success" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-sm btn-info" %>
      <% end %>
    <% end %>
    <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
      <%= link_to 'chatを始める', chat_path(user.id), class: "ml-3" %>
    <% end %>
  </div>
  <div class="form-body my-2">
    <h2>New book</h2>
    <%= form_with model:book,local:true do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control book_title' %>
      </div>
      <div class="form-group">
        <%= f.label :opinion %>
        <%= f.text_area :body, class: 'form-control book_body' %>
      </div>
      <div class="form-group" id="star">
        <%= f.label :rate %>
        <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>
      </div>
      <script>
        $('#star').raty({
          size     : 36,
          starOff:  '<%= asset_path('star-off.png') %>',
          starOn : '<%= asset_path('star-on.png') %>',
          starHalf: '<%= asset_path('star-half.png') %>',
          scoreName: 'book[rate]',
          half: true,
        });
      </script>
      <div class="form-group">
        <%= f.submit class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class="form-body p-4">
        <h2>Editing Book</h2>
        <div class="error">
            <% if @book.errors.any? %>
              <%= @book.errors.count %> errors prohibited this obj from being saved:
              <% @book.errors.full_messages.each do |message| %>
              <ul>
                <li><%= message %></li>
              </ul>
            <% end %>
          <% end %>
        </div>
        <%= form_with model: @book, local: true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title, class: "form-control" %>
          <h4>Opinion</h4>
          <%= f.text_area :body, class: "form-control", rows: "3" %>
          <div id="rate_<%= @book.id %>"></div>
          <script>
            $('#rate_<%= @book.id %>').raty({
              size: 20,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= @book.rate %>,
            });
          </script>
          <%= f.submit 'Update Book', class:"btn btn-sm btn-success my-3" %>
        <% end %>
        <%= link_to "Show", book_path(@book) %>
        <span>|</span>
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="error">
  <% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this obj from being saved:
  <% @book.errors.full_messages.each do |message| %>
    <ul>
      <li><%= message %></li>
    </ul>
  <% end %>
<% end %>
</div>
<div class="container px-5 px-sm-0 py-3">
  <div class="row">
    <%= render 'books/list', book: @book, user: current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= link_to "新しい順", books_path(sort: 'new') %> |
      <%= link_to "古い順", books_path(sort: 'old') %> |
      <%= link_to "評価の高い順", books_path(sort: 'high') %>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr id="book_<%= book.id %>">
            <td>
              <%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <td class="favorite-btn">
              <%= render 'favorites/favorite-btn', book: book %>
            </td>
            <td>コメント数：<%= book.book_comments.count %></td>
            <td>
              <div id="rate_<%= book.id %>"></div>
              <script>
                $('#rate_<%= book.id %>').raty({
                  size: 20,
                  starOff:  '<%= asset_path('star-off.png') %>',
                  starOn : '<%= asset_path('star-on.png') %>',
                  starHalf: '<%= asset_path('star-half.png') %>',
                  half: true,
                  readOnly: true,
                  score: <%= book.rate %>,
                });
              </script>
    				</td>
    				<td>閲覧数: <%= book.impressionist_count %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0 py-3">
    <div class="row">
      <%= render 'books/list', book: Book.new, user: @book.user %>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr id="book_<%= @book.id %>">
              <td>
                <%= attachment_image_tag @book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %><br>
                <%= link_to @book.user.name, user_path(@book.user_id) %>
              </td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>
              <td class="favorite-btn">
                <%= render 'favorites/favorite-btn', book: @book %>
              </td>
              <td><p class="comments-count">コメント数：<%= @book.book_comments.count %></p></td>
              <td>
                <div id="rate_<%= @book.id %>"></div>
                <script>
                  $('#rate_<%= @book.id %>').raty({
                    size: 20,
                    starOff:  '<%= asset_path('star-off.png') %>',
                    starOn : '<%= asset_path('star-on.png') %>',
                    starHalf: '<%= asset_path('star-half.png') %>',
                    half: true,
                    readOnly: true,
                    score: <%= @book.rate %>,
                  });
                </script>
              </td>
              <td>閲覧数: <%= @book.impressionist_count %></td>
              <% if @book.user.id == current_user.id %>
                <td><%= link_to "Edit", edit_book_path(@book), class:"btn btn-sm btn-success" %></td>
                <td><%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <table id="book_comments">
          <%= render 'book_comments/index', book: @book %>
        </table>
        <%= form_with model:[@book,@book_comment] do |f| %>
          <%= f.text_area :comment, size:"90x5" %><br>
          <%= f.submit '送信'%>
        <% end %>
      </div>
    </div>
  </div>

app/views/chats/show.html.erb
<h1><%= @user.name %> さんとのチャット</h1>
<div style="width: 400px;">
  <% @chats.each do |chat| %>
    <% if chat.user_id == current_user.id %>
      <p style="text-align: right;"><%= chat.message %></p>
    <% else %>
      <p style="text-align: left;"><%= chat.message %></p>
    <% end %>
  <% end %>
</div>
<%= form_with model: @chat, local: true do |f| %>
  <%= f.text_field :message %>
  <%= f.hidden_field :room_id %>
<% end %>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class='table table-bordered'>
  <thead>
    <tr> 
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= search_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <div class="form-body p-4">
        <h2>User info</h2>
        <div class="error">
          <% if @user.errors.any? %>
            <%= @user.errors.count %> errors prohibited this obj from being saved:
            <% @user.errors.full_messages.each do |message| %>
            <ul>
              <li><%= message %></li>
            </ul>
            <% end %>
          <% end %>
        </div>
        <%= form_with model: @user, local: true do |f| %>
          <h4>Name</h4>
          <%= f.text_field :name, class: "form-control" %>
          <h4>Image</h4>
          <%= f.attachment_field :profile_image, class: "py-2" %>
          <h4>Introduction</h4>
          <%= f.text_area :introduction, class: "form-control", rows: "2" %>
          <%= f.submit 'Update User', class: "btn btn-sm btn-secondary my-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0 py-3">
  <div class="row">
    <%= render 'books/list', book: @book, user: current_user %>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <%= link_to "グループ作成", new_group_path %> |
      <%= link_to "グループ一覧", groups_path %>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
            </td>
            <td><%= user.name %></td>
            <td>フォロー数: <%= user.followings.count %></td>
            <td>フォロワー数: <%= user.followers.count %></td>
            <td>
              <% if current_user != user %>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:"btn btn-sm btn-success" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class:"btn btn-sm btn-info" %>
                <% end %>
              <% end %>
            </td>
            <td>
              <%=link_to "Show", user_path(user), class:"btn btn-sm btn-primary"  %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$("#search_result").html("<%= j(render 'search', search_book: @search_book) %>");

app/views/users/show.html.erb
<div class="container px-5 px-sm-0 py-3">
  <div class="row">
  <%= render 'books/list', book: @book, user: @user %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%= link_to user_path(@user) do %>
              <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg" %>
            <% end %>
          </td>
          <td><%= link_to book.title, book_path(book) %></td>
          <td><%= book.body %></td>
          <td>コメント数：<%= book.book_comments.count %></td>
          <td>
            <div id="rate_<%= book.id %>"></div>
            <script>
              $('#rate_<%= book.id %>').raty({
                size: 20,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= book.rate %>,
              });
            </script>
          </td>
          <td>閲覧数: <%= book.impressionist_count %></td>
        </tr>
        <% end %>
      </table>
      <div class="my-3">
        <%= form_with url: user_search_path(@user), method: :get do |f| %>
          <%= f.date_field :created_at %>
          <%= f.submit '検索', class: 'btn btn-primary'  %>
        <% end %>
      </div>
      <div id="search_result">
        <% if @search_book.present? %>
          <%= render 'search', search_book: @search_book %>
        <% end %>
      </div>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_books.count %></td>
            <td><%= @yesterday_books.count %></td>
            <td>
              <% if @yesterday_books.count == 0 %>
                前日の投稿が0のため計算できません
              <% else %>
                <%= (@today_books.count / @yesterday_books.count) * 100 %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>前週の投稿数</th>
            <th>前週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @this_week_books.count %></td>
            <td><%= @last_week_books.count %></td>
            <td>
              <% if @last_week_books.count == 0 %>
                前週の投稿が0のため計算できません
              <% else %>
                <%= (@this_week_books.count / @last_week_books.count) * 100 %>%
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <h4>7日間分の投稿数</h4>
      <table class='table table-bordered'>
        <thead>
          <tr>
            <th>６日前</th>
            <th>５日前</th>
            <th>４日前</th>
            <th>３日前</th>
            <th>２日前</th>
            <th>１日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @books.created_6day_ago.count %></td>
            <td><%= @books.created_5day_ago.count %></td>
            <td><%= @books.created_4day_ago.count %></td>
            <td><%= @books.created_3day_ago.count %></td>
            <td><%= @books.created_2day_ago.count %></td>
            <td><%= @books.created_yesterday.count %></td>
            <td><%= @books.created_today.count %></td>
          </tr>
        </tbody>
      </table>
      <canvas id="myLineChart"></canvas>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
      <script>
        $(document).on('turbolinks:load', function() {
          var ctx = document.getElementById("myLineChart");
          var myLineChart = new Chart(ctx, {
            type: 'line',
            data: {
              labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
              datasets: [
                {
                  label: '投稿した本の数',
                  data: [<%= @books.created_6day_ago.count %>, <%= @books.created_5day_ago.count %>, <%= @books.created_4day_ago.count %>, <%= @books.created_3day_ago.count %>, <%= @books.created_2day_ago.count %>, <%= @books.created_yesterday.count %>, <%= @books.created_today.count %>],
                  borderColor: "rgba(0,0,255,1)",
                  backgroundColor: "rgba(0,0,0,0)"
                }
              ],
            },
            options: {
              title: {
                display: true,
                text: '7日間の投稿数の比較'
              },
              scales: {
                yAxes: [{
                  ticks: {
                    suggestedMax: 10,
                    suggestedMin: 0,
                    stepSize: 1,
                    callback: function(value, index, values){
                      return  value
                    }
                  }
                }]
              },
            }
          });
        });
      </script>
    </div>
  </div>
</div>